let str ="Hello World"
console.log(str)

let s1="this is harsh's string"
let s2="this is harsh\'s string";

console.log(s1);
console.log(s2);


// Use of Backticks
let p='HArsh'
let stri = `this is ${p} string`;
console.log(stri);


// string line break
let longst='this is\
a very long\
string'
console.log(longst)


// Functons

//Searching
let s='this has some data here'
let key="some"
console.log(s.indexOf(key));

// String Methods

let mainstr= "this is a long string"
let smallstr= mainstr.slice(2,6)

console.log(smallstr)

let sstr=mainstr.substring(7,10)
console.log(sstr)
let mstr=mainstr.slice(-4,-6)
console.log(mstr)







